build:
  commands:
    - python3 -m venv .venv
    - .venv/bin/pip install --upgrade pip setuptools wheel
    - .venv/bin/pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
    - .venv/bin/pip install -r requirements.txt
start: .venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8