build:
  commands:
    - python3 -m venv .venv
    - .venv/bin/pip install --upgrade pip setuptools wheel
    - .venv/bin/pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
    - .venv/bin/pip install -r requirements.txt
    - .venv/bin/pip install gunicorn
    - .venv/bin/python -c "import torch; print('Torch OK:', torch.__version__)"

start: .venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --workers 1
